cov0.05
err_rate1
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(decodeXwithSeqErr.py:1235603): Gdk-CRITICAL **: 16:32:24.569: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
rm: cannot remove './simulated/1000G_Mosaic/TSI/maleXseqErr2/chrX_cov1over20/err1/iid*': No such file or directory
